org.gradle.jvmargs=-Xmx8192M
org.gradle.parallel=true

# mod properties
archives_name=plushies
mod_version=1.5.2
maven_group=com.link
enabled_platforms=fabric,neoforge

# minecraft properties
minecraft_version=1.21.5

# dependencies
architectury_version=16.1.4
fabric_loader_version=0.16.10
fabric_version=0.128.2+1.21.5
neoforge_version=21.5.95
