modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Link4real/Plushie-Mod/issues"
license = "MIT"

[[mods]]
modId = "plushies"
version = "${version}"
displayName = "Plushie Mod"
authors = "Link4real, Vento"
description = '''
Adds a lot of cute Plushies to the game :)
'''
logoFile = "assets/plushies/icon.png"

[[dependencies.plushies]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.plushies]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.plushies]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"
